version: "3.8"

services:

  db:
    image: postgres:alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - db.env
    # command: startup.sh
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    env_file: db.env
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
    db_data: